name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install -e ".[test,dev]"
    
    - name: Lint with ruff
      run: |
        python lint_check.py
    
    - name: Test with pytest
      run: |
        python run_coverage.py
      env:
        MIN_COVERAGE: 70
    
    - name: Build package
      run: |
        pip install build
        python -m build
        
    - name: Check package
      run: |
        pip install twine
        twine check dist/*
